### ISSUE TITLE
Docs Examples Out of Date

### ISSUE THREAD

**Issue by brooksbecton** [mfrachet/rn-placeholder#100]
https://mfrachet.github.io/rn-placeholder/components/line.html
1 example of the the docs using the old API. 

I don't mind jumping on this.

**Comment by mfrachet** [comment]
Can you please remove your cache ? The site was using a tool called vuepress heavily relying on caching mechanism that I ve moved 😅

**Comment by brooksbecton** [comment]
![Screen Shot 2019-08-21 at 3 50 09 PM](https://user-images.githubusercontent.com/9373516/63463547-5fb75900-c42b-11e9-8cef-12e395aa1a89.png)

It did update today to this site. 
Are you moving away from the previous style of website? 

We just upgraded from v1 -> v3 and it was a little confusing seeing the v1 site and then this site that gives a few examples. 

We were looking for things like animations and Paragraph components and I had to go through the code to see how they were being used or if it still existed.

**Comment by mfrachet** [comment]
Absolutely 😊 . The previous site had a lot of content because the library was built in a way that wasn't that much extensible and needed more explanations.

Since the new version of the library is only providing three components: `Line`, `Media` and `Placeholder`, I wanted to provide as few information for the v3 usage as possible and this is the reason there's nothing more that this single page 😓 

Maybe what's missing here is a migration guide?

What are you looking for exactly?

Thanks for your feedbacks, I'll try to make something that work for you and other people 💪 !

**Comment by brooksbecton** [comment]
Custom Animations and Animation Duration.

https://github.com/mfrachet/rn-placeholder/blob/master/src/animations/Shine.tsx#L43
I saw this prop coming through on animations and wanted to use it. 
I tried something like 
```
<Placeholder   Animation={() => <Fade duration={1500}/>} >{...}<Placeholder/>
```
but had no luck. 

I ended up just copy/pasting the whole Shine component and changing the default. 


Kinda similar situation for custom animations. I just copy and pasted one of the animations and tweaked the numbers around, but didn't really understand how some it was working. 
_This one may just have to be me digging around the code some more._

**Comment by mfrachet** [comment]
I don't forget, I'm actually working on a documentation 😅 sorry for being that late again

**Comment by mfrachet** [comment]
https://mfrachet.github.io/rn-placeholder/ is now updated. Make sure you've cleared your cache before refreshing.

Let me know if you're waiting for more informations 😊 .

I'll make the website folder as a git submodule soon for contributions 😊
