### ISSUE TITLE
error during render

### ISSUE THREAD

**Issue by club9822** [mfrachet/rn-placeholder#102]
i copy pasted  basic example and this is error i faced

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

"react": "16.8.3",
 "react-native": "0.59.10",
"rn-placeholder": "^3.0.0"

**Comment by mfrachet** [comment]
Can you show the code you have copied ? Thanks 😊

**Comment by club9822** [comment]
thanks to your response
i copy pasted this example.
https://github.com/mfrachet/rn-placeholder/blob/master/example/storybook/stories/elements.tsx
 

could you say why whenReadyRender is removed? 
and alternative way to manually hide placeholders?

thanks to this awesome work. 😊

**Comment by mfrachet** [comment]
Did you try to copy paste everything from a story?

Because `Card` and `Title` are not exported by the module.

I'm actually writing some documentation to close https://github.com/mfrachet/rn-placeholder/issues/100 .

And there will be a section on what has change between the older version and the v3. 😊
