### ISSUE TITLE
Works with react native 0.40.0 version ?

### ISSUE THREAD

**Issue by rodolfobarretoweb** [mfrachet/rn-placeholder#24]
I try to implement in my project  but get this error:

![screen shot 2017-09-19 at 17 41 19](https://user-images.githubusercontent.com/914032/30614481-ea902018-9d61-11e7-9fa6-a0196e8ad125.png)

**Comment by rodolfobarretoweb** [comment]
My code implementation

`return(
      <View style = { Style.container }>
        <Header backButton
          actionButton         = { permissions.check('schedules', CREATE) }
          title                = { title }
          onBackButtonPress    = { this._popNavigation }
          actionButtonIconName = 'add'
          onActionButtonPress  = { this._goToScheduleForm }
        />
          <ScrollView>
            <Text style = { Style.dateSelectLabel }>
              { formatDateToDisplay(this.props.data.dateSelect, 'dddd, LL') }
            </Text>

            <Placeholder.ImageContent
              onReady       = { false }
              lineNumber    = {2}
              animate       = "fade"
              lastLineWidth = "40%"
            >
              { this._renderList() }
            </Placeholder.ImageContent>
          </ScrollView>
      </View>
    );`

**Comment by mfrachet** [comment]
It seems that using styles with string concerning height and width are not supported on the Yoga version used by React Native 0.40.

Maybe it can be helpful : https://github.com/facebook/yoga/pull/258

I'll try to make some tests from my side to use flex properties instead of percentage and give you some feedbacks when possible. 

Thanks for your help on the project 😄
