### ISSUE TITLE
How do I know my image has finished loading?

### ISSUE THREAD

**Issue by AideProjet** [mfrachet/rn-placeholder#77]
Hi, 

I'm sorry this is a simple question but: how can I know if my image is fully loaded if the component containing the image has not yet been loaded? 

How do you use this library to have a placeholder until your content is loaded? 

Thanks, 

Théo

**Comment by mfrachet** [comment]
Your question is not that simple and actually reflects the biggest difficulty I have to deal with 😊. Since the Placeholder will only add its children to the view **only when the isReady props is true**, the Image will only start downloading its assets at that time.

What I mean here is that you won't be able to rely on the children for image loading, so this wont work:

```jsx
<View>
  <Placeholder.Media isReady={this.state.isReady}>
    <Image /> {'this will start downloading only when the state is true 😞'}
  </Placeholder.Media>
</View>
```

One workaround is to rely on the onLoad prop of the Image component, something like this (you should adjust this for your usecase): 

```jsx
<View>
  {hasImageLoaded && <Placeholder.Media />}
  <Image onLoad={() => this.setState({ hasImageLoaded: true })}
</View>
```

**Comment by mfrachet** [comment]
I close this for now, feel free to reopen 😊

**Comment by 32teeths** [comment]
Needed something similar .

**Comment by mfrachet** [comment]
Have you tried the new API? it doesn't rely anymore on the `isReady ` prop so maybe it can be better for you?
